DROP TABLE IF EXISTS CIIU_4_actividad;
CREATE TABLE IF NOT EXISTS CIIU_4_actividad(
   cod3dig VARCHAR(3) NOT NULL
  ,cod4dig VARCHAR(4) NOT NULL PRIMARY KEY
  ,CIIU      VARCHAR(117) NOT NULL
);
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('11','111','Cultivo de cereales y otros cultivos ncp');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('11','112','Cultivo de hortalizas y legumbres, especialidades hortícolas y productos de vivero');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('11','113','Cultivo de frutas, nueces, plantas cuyas hojas o frutas se utilizan para preparar bebidas, y especia');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('12','121','Cría de ganado vacuno y de ovejas, cabras, caballos, asnos, mulas y burdéganos; cría de ganado leche');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('12','122','Cría de otros animales, elaboración de productos animales ncp');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('20','200','Silvicultura, extracción de madera y actividades de servicios conexas');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('50','500','Pesca, explotación de criaderos de peces y granjas piscícolas; actividades de servicios relacionadas');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('101','1010','Extracción y aglomeración de carbón de piedra');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('102','1020','Extracción y aglomeración de lignito');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('103','1030','Extracción y aglomeración de turba');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('111','1110','Extracción de petróleo crudo y gas natural');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('120','1200','Extracción de minerales de uranio y torio');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('131','1310','Extracción de minerales de hierro');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('132','1320','Extracción de minerales metalíferos no ferrosos, excepto los minerales de uranio y torio');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('141','1410','Extracción de piedra, arena y arcilla');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('142','1421','Extracción de minerales para la fabricación de abonos y productos químicos');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('142','1422','Extracción de sal');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('142','1429','Explotación de otras minas y canteras ncp');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('151','1511','Producción, procesamiento y conservación de carne y productos cárnicos');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('151','1512','Elaboración y conservación de pescado y productos de pescado');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('151','1513','Elaboración y conservación de frutas, legumbres y hortalizas');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('151','1514','Elaboración de aceites y grasas de origen vegetal y animal');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('152','1520','Elaboración de productos lácteos');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('153','1531','Elaboración de productos de molinería');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('153','1532','Elaboración de almidones y productos derivados del almidón');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('153','1533','Elaboración de alimentos preparados para animales');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('154','1541','Elaboración de productos de panadería');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('154','1542','Elaboración de azúcar');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('154','1543','Elaboración de cacao y chocolate y de productos de confitería');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('154','1544','Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('154','1549','Elaboración de otros productos alimenticios ncp');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('155','1551','Destilación, rectificación y mezcla de bebidas alcohólicas; producción de alcohol etílico a partir d');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('155','1552','Elaboración de vinos');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('155','1553','Elaboración de bebidas malteadas y de malta');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('155','1554','Elaboración de bebidas no alcohólicas, producción de aguas minerales');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('160','1600','Elaboración de productos de tabaco');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('171','1711','Preparación e hilatura de fibras textiles, tejedura de productos textiles');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('172','1721','Fabricación de artículos confeccionados de materiales textiles, excepto prendas de vestir');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('172','1722','Fabricación de tapices y alfombras');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('172','1723','Fabricación de cuerdas, cordeles, bramantes y redes');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('172','1729','Fabricación de otros productos textiles ncp');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('173','1730','Fabricación de tejidos y artículos de punto y ganchillo');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('181','1810','Fabricación de prendas de vestir, excepto prendas de piel');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('182','1820','Adobo y teñido de pieles, fabricación de artículos de piel');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('191','1911','Curtido y adobo de cueros');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('191','1912','Fabricación de maletas, bolsos de mano y artículos similares, y de artículos de talabartería y guarn');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('192','1920','Fabricación de calzado');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('201','2010','Aserrado y acepilladura de madera');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('202','2021','Fabricación de hojas de madera para enchapado; fabricación de tableros contrachapados, tableros lami');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('202','2022','Fabricación de partes y piezas de carpintería para edificios y construcciones');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('202','2023','Fabricación de recipientes de madera');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('202','2029','Fabricación de otros productos de madera; fabricación de artículos de corcho, paja y materiales tren');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('210','2101','Fabricación de pasta de madera, papel y cartón');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('210','2102','Fabricación de papel y cartón ondulado y de envases de papel y cartón');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('210','2109','Fabricación de otros artículos de papel y cartón');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('221','2211','Edición de libros, folletos, partituras y otras publicaciones');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('221','2212','Edición de periódicos, revistas y publicaciones periódicas');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('221','2213','Edición de grabaciones');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('221','2219','Otras actividades de edición');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('222','2221','Actividades de impresión');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('222','2222','Actividades de servicios relacionadas con la impresión');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('231','2310','Fabricación de productos de hornos de coque');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('232','2320','Fabricación de productos de la refinación del petróleo');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('233','2330','Elaboración de combustible nuclear');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('241','2411','Fabricación de sustancias químicas básicas, excepto abonos y compuestos de nitrógeno');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('241','2412','Fabricación de abonos y compuestos de nitrógeno');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('241','2413','Fabricación de plásticos en formas primarias y de caucho sintítico');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('242','2421','Fabricación de plaguicidas y otros productos químicos de uso agropecuario');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('242','2422','Fabricación de pinturas, barnices y productos de revestimiento similares, tintas de imprenta y masil');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('242','2423','Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('242','2424','Fabricación de jabones y detergentes, preparados para limpiar y pulir, perfumes y preparados de toca');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('242','2429','Fabricación de otros productos químicos ncp');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('243','2430','Fabricación de fibras manufacturadas');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('251','2511','Fabricación de cubiertas y cámaras de caucho, recauchado y renovación de cubiertas de caucho');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('251','2519','Fabricación de otros productos de caucho');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('252','2520','Fabricación de productos de plástico');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('261','2610','Fabricación de vidrio y productos de vidrio');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('269','2691','Fabricación de productos de cerámica no refractaria para uso no estructural');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('269','2692','Fabricación de productos de cerámica refractaria');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('269','2693','Fabricación de productos de arcilla y cerámica no refractarias para uso estructural');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('269','2694','Fabricación de cemento, cal y yeso');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('269','2695','Fabricación de artículos de hormigón, cemento y yeso');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('269','2696','Corte, tallado y acabado de la piedra');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('269','2699','Fabricación de otros productos minerales no metálicos ncp');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('271','2710','Industrias básicas de hierro y acero');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('272','2720','Fabricación de productos primarios de metales preciosos y metales no ferrosos');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('281','2811','Fabricación de productos metálicos para uso estructural');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('281','2812','Fabricación de tanques, depósitos y recipientes de metal');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('281','2813','Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('289','2893','Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('289','2899','Fabricación de otros productos elaborados de metal ncp');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('291','2911','Fabricación de motores y turbinas, excepto motores para aeronaves, vehículos automotores y motocicle');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('291','2912','Fabricación de bombas, compresores, grifos y válvulas');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('291','2913','Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('291','2914','Fabricación de hornos, hogares y quemadores');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('291','2915','Fabricación de equipo de elevación y manipulación');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('291','2919','Fabricación de otros tipos de maquinaria de uso general');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('292','2921','Fabricación de maquinaria agropecuaria y forestal');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('292','2922','Fabricación de máquinas herramienta');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('292','2923','Fabricación de maquinaria metalúrgica');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('292','2924','Fabricación de maquinaria para la explotación de minas y canteras y para obras de construcción');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('292','2925','Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('292','2926','Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('292','2927','Fabricación de armas y municiones');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('292','2929','Fabricación de otros tipos de maquinaria de uso especial');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('293','2930','Fabricación de aparatos de uso doméstico ncp');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('300','3000','Fabricación de maquinaria de oficina, contabilidad e informática');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('311','3110','Fabricación de motores, generadores y transformadores eléctricos');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('312','3120','Fabricación de aparatos de distribución y control de la energía eléctrica');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('313','3130','Fabricación de hilos y cables aislados');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('314','3140','Fabricación de acumuladores y de pilas y baterías primarias');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('315','3150','Fabricación de lámparas eléctricas y equipo de iluminación');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('319','3190','Fabricación de otros tipos de equipo eléctrico ncp');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('321','3210','Fabricación de tubos y válvulas electrónicos y de otros componentes electrónicos');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('322','3220','Fabricación de transmisores de radio y televisión y de aparatos para telefonía y telegrafía con hilo');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('323','3230','Fabricación de receptores de radio y televisión, aparatos de grabación y reproducción de sonido y ví');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('331','3311','Fabricación de equipo médico y quirúrgico y de aparatos ortopédicos');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('331','3312','Fabricación de instrumentos y aparatos para medir, verificar, ensayar, navegar y otros fines, except');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('331','3313','Fabricación de equipo de control de procesos industriales');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('332','3320','Fabricación de instrumentos de óptica y equipo fotográfico');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('333','3330','Fabricación de relojes');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('341','3410','Fabricación de vehículos automotores');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('342','3420','Fabricación de carrocerías para vehículos automotores, fabricación de remolques y semirremolques');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('343','3430','Fabricación de partes, piezas y accesorios para vehículos automotores y sus motores');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('351','3511','Construcción y reparación de buques');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('351','3512','Construcción y reparación de embarcaciones de recreo y deporte');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('352','3520','Fabricación de locomotoras y de material rodante para ferrocarriles y tranvías');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('353','3530','Fabricación de aeronaves y naves espaciales');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('359','3591','Fabricación de motocicletas');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('359','3592','Fabricación de bicicletas y de sillones de ruedas para inválidos');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('359','3599','Fabricación de otros tipos de equipo de transporte ncp');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('361','3610','Fabricación de muebles');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('369','3691','Fabricación de joyas y artículos conexos');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('369','3692','Fabricación de instrumentos de música');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('369','3693','Fabricación de artículos de deporte');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('369','3694','Fabricación de juegos y juguetes');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('369','3699','Otras industrias manufactureras ncp');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('401','4010','Generación, captación y distribución de energía eléctrica');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('402','4020','Fabricación de gas, distribución de combustibles gaseosos por tuberías');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('722','7221','Edición de programas de informática');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('742','7421','Actividades de arquitectura e ingeniería y actividades conexas de asesoramiento técnico');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('749','7494','Actividades de fotografía');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('921','9211','Producción y distribución de filmes y videocintas');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('921','9214','Actividades teatrales y musicales y otras actividades artísticas');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('930','9302','Peluquería y otros tratamientos de belleza');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('S/C','S/C','SIN CLASIFICAR');
INSERT INTO CIIU_4_actividad(cod3dig,cod4dig,CIIU) VALUES ('IND','IND','Indeterminado');
