DROP TABLE IF EXISTS CIIU_3_rama;
CREATE TABLE IF NOT EXISTS CIIU_3_rama(
   cod2dig VARCHAR(3) NOT NULL
  ,cod3dig VARCHAR(3) NOT NULL PRIMARY KEY
  ,CIIU      VARCHAR(100) NOT NULL
);
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('1','11','Cultivos en general');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('1','12','Cría de animales');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('2','20','Silvicultura, extracción de madera y actividades de servicios conexas');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('5','50','Pesca, explotación de criaderos de peces y granjas piscícolas; actividades de servicios relacionadas');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('10','101','Extracción y aglomeración de carbón de piedra');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('10','102','Extracción y aglomeración de lignito');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('10','103','Extracción y aglomeración de turba');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('11','111','Extracción de petróleo crudo y gas natural');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('12','120','Extracción de minerales de uranio y torio');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('13','131','Extracción de minerales de hierro');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('13','132','Extracción de minerales metalíferos no ferrosos, excepto los minerales de uranio y torio');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('14','141','Extracción de piedra, arena y arcilla');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('14','142','Explotación de minas y canteras ncp');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('15','151','Producción, procesamiento y conservación de carne, pescado, frutas, legumbres, hortalizas, aceites y');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('15','152','Elaboración de productos lácteos');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('15','153','Elaboración de productos de molinería, almidones y productos derivados del almidón, y de alimentos p');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('15','154','Elaboración de otros productos alimenticios');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('15','155','Elaboración de bebidas');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('16','160','Elaboración de productos de tabaco');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('17','171','Hilatura, tejedura y acabado de productos textiles');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('17','172','Fabricación de otros productos textiles');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('17','173','Fabricación de tejidos y artículos de punto y ganchillo');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('18','181','Fabricación de prendas de vestir, excepto prendas de piel');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('18','182','Adobo y teñido de pieles');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('19','191','Curtido y adobo de cueros; fabricación de maletas, bolsos de mano y artículos de talabartería y guar');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('19','192','Fabricación de calzado');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('20','201','Aserrado y acepilladura de madera');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('20','202','Fabricación de productos de madera, corcho, paja y materiales trenzables');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('21','210','Fabricación de papel y de productos de papel');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('22','221','Actividades de edición');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('22','222','Actividades de impresión y actividades de servicios conexas');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('23','231','Fabricación de productos de hornos de coque');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('23','232','Fabricación de productos de la refinación del petróleo');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('23','233','Elaboración de combustible nuclear');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('24','241','Fabricación de sustancias químicas básicas');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('24','242','Fabricación de otros productos químicos');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('24','243','Fabricación de fibras manufacturadas');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('25','251','Fabricación de productos de caucho');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('25','252','Fabricación de productos de plástico');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('26','261','Fabricación de vidrio y productos de vidrio');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('26','269','Fabricación de productos minerales no metálicos ncp');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('27','271','Industrias básicas de hierro y acero');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('27','272','Fabricación de productos primarios de metales preciosos y metales no ferrosos');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('28','281','Fabricación de productos metálicos para uso estructural, tanques, depósitos y generadores de vapor');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('28','289','Fabricación de otros productos elaborados de metal');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('29','291','Fabricación de maquinaria de uso general');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('29','292','Fabricación de maquinaria de uso especial');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('29','293','Fabricación de aparatos de uso doméstico ncp');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('30','300','Fabricación de maquinaria de oficina, contabilidad e informática');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('31','311','Fabricación de motores, generadores y transformadores eléctricos');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('31','312','Fabricación de aparatos de distribución y control de la energía eléctrica');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('31','313','Fabricación de hilos y cables aislados');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('31','314','Fabricación de acumuladores y de pilas y baterías primarias');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('31','315','Fabricación de lámparas eléctricas y equipo de iluminación');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('31','319','Fabricación de otros tipos de equipo eléctrico ncp');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('32','321','Fabricación de tubos y válvulas electrónicos y de otros componentes electrónicos');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('32','322','Fabricación de transmisores de radio y televisión y de aparatos para telefonía y telegrafía con hilo');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('32','323','Fabricación de receptores de radio y televisión, aparatos de grabación y reproducción de sonido y ví');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('33','331','Fabricación de aparatos e instrumentos médicos y de aparatos para medir, verificar, ensayar, navegar');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('33','332','Fabricación de instrumentos de óptica y equipo fotográfico');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('33','333','Fabricación de relojes');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('34','341','Fabricación de vehículos automotores');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('34','342','Fabricación de carrocerías para vehículos automotores');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('34','343','Fabricación de partes, piezas y accesorios para vehículos automotores y sus motores');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('35','351','Construcción y reparación de buques y otras embarcaciones');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('35','352','Fabricación de locomotoras y de material rodante para ferrocarriles y tranvías');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('35','353','Fabricación de aeronaves y naves espaciales');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('35','359','Fabricación de otros tipos de equipo de transporte ncp');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('36','361','Fabricación de muebles');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('36','369','Industrias manufactureras ncp');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('40','401','Generación, captación y distribución de energía eléctrica');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('40','402','Fabricación de gas');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('72','722','Edición de programas de informática, consultores en programas de informática y suministro de programas de informática');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('74','742','Actividades de arquitectura e ingeniería y otras actividades técnicas');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('74','749','Actividades empresariales ncp');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('92','921','Actividades de cinematografía, radio y televisión y otras actividades de entretenimiento');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('93','930','Otras actividades de servicios');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('S/C','S/C','SIN CLASIFICAR');
INSERT INTO CIIU_3_rama(cod2dig,cod3dig,CIIU) VALUES ('IND','IND','Indeterminado');
